config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  require 'sidekiq_unique_jobs/web'

  mount Sidekiq::Web => '/sidekiq', constraints: AdminRouteConstraint.new

  namespace :admin do
    resources :users, :only => [:edit, :update, :edit_blacklist, :update_blacklist, :alt_list] do
      member do
        get :edit_blacklist
        post :update_blacklist
        get :request_password_reset
        post :password_reset
      end
      collection do
        get :alt_list
      end
    end
    resource :dashboard, :only => [:show]
    resources :exceptions, only: [:index, :show]
    resource :reowner, controller: 'reowner', only: [:new, :create]
    resources :staff_notes, only: [:index]
    resources :danger_zone, only: [:index] do
      collection do
        put :uploading_limits
      end
    end
  end
  resources :edit_histories
  namespace :moderator do
    resource :dashboard, :only => [:show]
    resources :ip_addrs, :only => [:index] do
      collection do
        get :export
      end
    end
    namespace :post do
      resource :approval, :only => [:create, :destroy]
      resources :disapprovals, :only => [:create, :index]
      resources :posts, :only => [:delete, :undelete, :expunge, :confirm_delete] do
        member do
          get :confirm_delete
          post :expunge
          post :delete
          post :undelete
          get :confirm_move_favorites
          post :move_favorites
          get :confirm_ban
          post :ban
          post :unban
          post :regenerate_thumbnails
          post :regenerate_videos
        end
      end
    end
  end
  resources :popular, only: [:index]
  namespace :maintenance do
    namespace :user do
      resource :count_fixes, only: [:new, :create]
      resource :email_notification, :only => [:show, :destroy]
      resource :password_reset, :only => [:new, :create, :edit, :update]
      resource :login_reminder, :only => [:new, :create]
      resource :deletion, :only => [:show, :destroy]
      resource :email_change, :only => [:new, :create]
      resource :dmail_filter, :only => [:edit, :update]
      resource :api_key, :only => [:show, :view, :update, :destroy] do
        post :view
      end
    end
  end

  resources :tickets do
    member do
      post :claim
      post :unclaim
    end
  end

  resources :takedowns do
    collection do
      post :count_matching_posts
    end
    member do
      post :add_by_ids
      post :add_by_tags
      post :remove_by_ids
    end
  end

  resources :artists do
    member do
      put :revert
    end
    collection do
      get :show_or_new
    end
  end
  resources :artist_urls, only: [:index, :update]
  resources :artist_versions, :only => [:index] do
    collection do
      get :search
    end
  end
  resources :bans
  resources :bulk_update_requests do
    member do
      post :approve
    end
  end
  resources :comments do
    resource :votes, :controller => "comment_votes", :only => [:create, :destroy]
    collection do
      get :search
    end
    member do
      post :hide
      post :unhide
      post :warning
    end
  end
  resources :comment_votes, only: [:index, :delete, :lock] do
    collection do
      post :lock
      post :delete
    end
  end
  resources :dmails, :only => [:new, :create, :index, :show, :destroy] do
    collection do
      post :mark_all_as_read
    end
  end
  resource :dtext_preview, :only => [:create]
  resources :favorites, :only => [:index, :create, :destroy]
  resources :forum_posts do
    resource :votes, controller: "forum_post_votes"
    member do
      post :hide
      post :unhide
      post :warning
    end
    collection do
      get :search
    end
  end
  resources :forum_topics do
    member do
      post :hide
      post :unhide
      post :subscribe
      post :unsubscribe
    end
    collection do
      post :mark_all_as_read
    end
    resource :visit, :controller => "forum_topic_visits"
  end
  resources :forum_categories
  resources :help_pages, controller: "help", path: "help"
  resources :ip_bans
  resources :upload_whitelists do
    collection do
      get :is_allowed
    end
  end
  resources :email_blacklists, only: [:new, :create, :destroy, :index]
  resource :iqdb_queries, :only => [:show] do
    collection do
      post :show
      get :preview
      get :check, to: redirect {|path_params, req| "/iqdb_queries?#{req.query_string}"}
    end
  end
  resources :mod_actions
  resources :news_updates
  resources :notes do
    collection do
      get :search
    end
    member do
      put :revert
    end
  end
  resources :note_versions, :only => [:index]
  resource :note_previews, :only => [:show]
  resources :pools do
    member do
      put :revert
    end
    collection do
      get :gallery
    end
    resource :order, :only => [:edit], :controller => "pool_orders"
  end
  resource :pool_element, :only => [:create, :destroy]
  resources :pool_versions, :only => [:index] do
    member do
      get :diff
    end
  end
  resources :post_replacements, :only => [:index, :new, :create, :destroy] do
    member do
      put :approve
      put :reject
      post :promote
      put :toggle_penalize
    end
  end
  resources :deleted_posts, only: [:index]
  resources :posts, :only => [:index, :show, :update] do
    resources :replacements, :only => [:index, :new, :create], :controller => "post_replacements"
    resource :votes, :controller => "post_votes", :only => [:create, :destroy]
    resource :flag, controller: 'post_flags', only: [:destroy]
    resources :favorites, :controller => "post_favorites", :only => [:index]
    collection do
      get :random
    end
    member do
      get :update_iqdb
      put :revert
      put :copy_notes
      get :show_seq
      put :mark_as_translated
      get :comments, to: "comments#for_post"
    end
    get :similar, :to => "iqdb_queries#index"
  end
  resources :post_votes, only: [:index, :delete, :lock] do
    collection do
      post :lock
      post :delete
    end
  end
  resources :post_events, only: :index
  resources :post_flags, except: [:destroy]
  resources :post_approvals, only: [:index]
  resources :post_versions, :only => [:index] do
    member do
      put :undo
    end
  end
  resource :related_tag, :only => [:show, :update]
  match "related_tag/bulk", to: "related_tags#bulk", via: [:get, :post]
  resource :session, only: [:new, :create, :destroy]
  resources :stats, only: [:index]
  resources :tags do
    resource :correction, :only => [:new, :create, :show], :controller => "tag_corrections"
    collection do
      get :autocomplete
      post :preview
    end
  end
  resources :tag_type_versions
  resources :tag_aliases do
    member do
      post :approve
    end
  end
  resource :tag_alias_request, :only => [:new, :create]
  resources :tag_implications do
    member do
      post :approve
    end
  end
  resource :tag_implication_request, :only => [:new, :create]
  resources :uploads
  resources :users do
    resource :password, :only => [:edit], :controller => "maintenance/user/passwords"
    resource :api_key, :only => [:show, :view, :update, :destroy], :controller => "maintenance/user/api_keys" do
      post :view
    end
    resources :staff_notes, only: [:index, :new, :create], controller: "admin/staff_notes"

    collection do
      get :home
      get :search
      get :upload_limit
      get :custom_style
    end
  end
  resources :user_feedbacks do
    collection do
      get :search
    end
  end
  resources :user_name_change_requests
  resource :user_revert, :only => [:new, :create]
  resources :wiki_pages do
    member do
      put :revert
    end
    collection do
      get :search
      get :show_or_new
    end
  end
  resources :wiki_page_versions, :only => [:index, :show, :diff] do
    collection do
      get :diff
    end
  end
  resources :blips do
    member do
      post :hide
      post :unhide
      post :warning
    end
  end
  resources :post_report_reasons
  resources :post_sets do
    collection do
      get :for_select
    end
    member do
      get :maintainers
      get :post_list
      post :update_posts
      post :add_posts
      post :remove_posts
    end
  end
  resources :post_set_maintainers do
    member do
      get :approve
      get :block
      get :deny
    end
  end
  resource :email do
    collection do
      get :activate_user
      get :resend_confirmation
    end
  end
  resources :mascots, only: [:index, :new, :create, :edit, :update, :destroy]

  options "*all", to: "application#enable_cors"

  # aliases
  resources :wpages, :controller => "wiki_pages"
  resources :ftopics, :controller => "forum_topics"
  resources :fposts, :controller => "forum_posts"

  # legacy aliases
  get "/artist" => redirect {|params, req| "/artists?page=#{req.params[:page]}&search[name]=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/index" => redirect {|params, req| "/artists?page=#{req.params[:page]}"}
  get "/artist/show/:id" => redirect("/artists/%{id}")
  get "/artist/show" => redirect {|params, req| "/artists?name=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/history/:id" => redirect("/artist_versions?search[artist_id]=%{id}")
  get "/artist/recent_changes" => redirect("/artist_versions")

  get "/comment" => redirect {|params, req| "/comments?page=#{req.params[:page]}"}
  get "/comment/index" => redirect {|params, req| "/comments?page=#{req.params[:page]}"}
  get "/comment/show/:id" => redirect("/comments/%{id}")
  get "/comment/new" => redirect("/comments")
  get("/comment/search" => redirect do |params, req|
    if req.params[:query] =~ /^user:(.+)/i
      "/comments?group_by=comment&search[creator_name]=#{CGI::escape($1)}"
    else
      "/comments/search"
    end
  end)

  get "/favorite" => redirect {|params, req| "/favorites?page=#{req.params[:page]}"}
  get "/favorite/index" => redirect {|params, req| "/favorites?page=#{req.params[:page]}"}

app/views/blips/partials/show/_blip.html.erb
<% if blip.visible_to?(CurrentUser.user) %>
  <article class="blip comment-post-grid" data-is-deleted="<%= blip.is_hidden? %>" data-creator="<%= blip.creator&.name.downcase %>"
           data-creator-id="<%= blip.creator_id %>">
    <div class="author-info">
      <div class="name-rank">
        <h4 class="author-name"><%= link_to_user blip.creator %></h4>
        <%= blip.creator.level_string %>
        <% if blip.is_hidden? %>
          (hidden)
        <% end %>
      </div>
      <div class="avatar">
        <%= user_avatar(blip.creator) %>
      </div>
      <div class="post-time">
        <%= link_to time_ago_in_words_tagged(blip.created_at), blip_path(blip) %>
      </div>
    </div>
    <div class="content">
      <% if blip.response? %>
        <h6><%= link_to "In response to blip ##{blip.response_to}", blip_path(id: blip.response_to) %> </h6>
      <% end %>
      <div class="body dtext-container">
        <%= format_text(blip.body, allow_color: blip.creator.is_privileged?) %>
      </div>
      <% if blip.was_warned? %>
        <div class="user-warning">
          <hr>
          <em><%= blip.warning_type_string %></em>
        </div>
      <% end %>
      <div class="content-menu">
        <menu>
          <% if CurrentUser.is_member? %>
            <li><%= tag.a "Reply", href: '#', class: 'blip-reply-link', 'data-bid': blip.id %></li>
            <% if blip.can_edit?(CurrentUser.user) %>
              <li><%= link_to "Edit", edit_blip_path(blip) %></li>
            <% end %>
            <li><%= tag.a "@", href: '#', class: 'blip-atme-link', 'data-bid': blip.id %></li>
          <% end %>

          <% if !blip.is_hidden && blip.can_hide?(CurrentUser.user) %>
            <li><%= link_to "Hide", hide_blip_path(blip), data: {confirm: "Are you sure you want to hide this blip?"}, method: :post %></li>
          <% elsif CurrentUser.is_moderator? %>
            <li><%= link_to "Unhide", unhide_blip_path(blip), data: {confirm: "Are you sure you want to unhide this blip?"}, method: :post %></li>
          <% end %>

          <% if CurrentUser.is_admin? %>
            <li><%= link_to "Delete", blip_path(blip), data: {confirm: "Are you sure you want to delete this blip?"}, method: :delete %></li>
          <% end %>

          <% if blip.has_responses? %>
            <li><%= link_to "View Responses", blip_path(blip) %></li>
          <% end %>

          <% if CurrentUser.is_member? %>
            <li><%= link_to "Report", new_ticket_path(disp_id: blip.id, qtype: 'blip') %></li>
          <% end %>

          <% if CurrentUser.is_moderator? %>
            <li>|</li>
            <li><%= link_to "Show Edits", edit_history_path(id: blip.id, type: 'Blip') %></li>
            <%= render "user_warnable/buttons", model: blip %>
          <% end %>
          <% if CurrentUser.is_admin? %>
            <li>|</li>
            <li>
              <strong>IP</strong>
              <span><%= link_to_ip blip.creator_ip_addr %></span>
            </li>
          <% end %>
        </menu>
      </div>
    </div>
  </article>
<% end %>