config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  require 'sidekiq_unique_jobs/web'

  mount Sidekiq::Web => '/sidekiq', constraints: AdminRouteConstraint.new

  namespace :admin do
    resources :users, :only => [:edit, :update, :edit_blacklist, :update_blacklist, :alt_list] do
      member do
        get :edit_blacklist
        post :update_blacklist
        get :request_password_reset
        post :password_reset
      end
      collection do
        get :alt_list
      end
    end
    resource :dashboard, :only => [:show]
    resources :exceptions, only: [:index, :show]
    resource :reowner, controller: 'reowner', only: [:new, :create]
    resources :staff_notes, only: [:index]
    resources :danger_zone, only: [:index] do
      collection do
        put :uploading_limits
      end
    end
  end
  resources :edit_histories
  namespace :moderator do
    resource :dashboard, :only => [:show]
    resources :ip_addrs, :only => [:index] do
      collection do
        get :export
      end
    end
    namespace :post do
      resource :approval, :only => [:create, :destroy]
      resources :disapprovals, :only => [:create, :index]
      resources :posts, :only => [:delete, :undelete, :expunge, :confirm_delete] do
        member do
          get :confirm_delete
          post :expunge
          post :delete
          post :undelete
          get :confirm_move_favorites
          post :move_favorites
          get :confirm_ban
          post :ban
          post :unban
          post :regenerate_thumbnails
          post :regenerate_videos
        end
      end
    end
  end
  resources :popular, only: [:index]
  namespace :maintenance do
    namespace :user do
      resource :count_fixes, only: [:new, :create]
      resource :email_notification, :only => [:show, :destroy]
      resource :password_reset, :only => [:new, :create, :edit, :update]
      resource :login_reminder, :only => [:new, :create]
      resource :deletion, :only => [:show, :destroy]
      resource :email_change, :only => [:new, :create]
      resource :dmail_filter, :only => [:edit, :update]
      resource :api_key, :only => [:show, :view, :update, :destroy] do
        post :view
      end
    end
  end

  resources :tickets do
    member do
      post :claim
      post :unclaim
    end
  end

  resources :takedowns do
    collection do
      post :count_matching_posts
    end
    member do
      post :add_by_ids
      post :add_by_tags
      post :remove_by_ids
    end
  end

  resources :artists do
    member do
      put :revert
    end
    collection do
      get :show_or_new
    end
  end
  resources :artist_urls, only: [:index, :update]
  resources :artist_versions, :only => [:index] do
    collection do
      get :search
    end
  end
  resources :bans
  resources :bulk_update_requests do
    member do
      post :approve
    end
  end
  resources :comments do
    resource :votes, :controller => "comment_votes", :only => [:create, :destroy]
    collection do
      get :search
    end
    member do
      post :hide
      post :unhide
      post :warning
    end
  end
  resources :comment_votes, only: [:index, :delete, :lock] do
    collection do
      post :lock
      post :delete
    end
  end
  resources :dmails, :only => [:new, :create, :index, :show, :destroy] do
    collection do
      post :mark_all_as_read
    end
  end
  resource :dtext_preview, :only => [:create]
  resources :favorites, :only => [:index, :create, :destroy]
  resources :forum_posts do
    resource :votes, controller: "forum_post_votes"
    member do
      post :hide
      post :unhide
      post :warning
    end
    collection do
      get :search
    end
  end
  resources :forum_topics do
    member do
      post :hide
      post :unhide
      post :subscribe
      post :unsubscribe
    end
    collection do
      post :mark_all_as_read
    end
    resource :visit, :controller => "forum_topic_visits"
  end
  resources :forum_categories
  resources :help_pages, controller: "help", path: "help"
  resources :ip_bans
  resources :upload_whitelists do
    collection do
      get :is_allowed
    end
  end
  resources :email_blacklists, only: [:new, :create, :destroy, :index]
  resource :iqdb_queries, :only => [:show] do
    collection do
      post :show
      get :preview
      get :check, to: redirect {|path_params, req| "/iqdb_queries?#{req.query_string}"}
    end
  end
  resources :mod_actions
  resources :news_updates
  resources :notes do
    collection do
      get :search
    end
    member do
      put :revert
    end
  end
  resources :note_versions, :only => [:index]
  resource :note_previews, :only => [:show]
  resources :pools do
    member do
      put :revert
    end
    collection do
      get :gallery
    end
    resource :order, :only => [:edit], :controller => "pool_orders"
  end
  resource :pool_element, :only => [:create, :destroy]
  resources :pool_versions, :only => [:index] do
    member do
      get :diff
    end
  end
  resources :post_replacements, :only => [:index, :new, :create, :destroy] do
    member do
      put :approve
      put :reject
      post :promote
      put :toggle_penalize
    end
  end
  resources :deleted_posts, only: [:index]
  resources :posts, :only => [:index, :show, :update] do
    resources :replacements, :only => [:index, :new, :create], :controller => "post_replacements"
    resource :votes, :controller => "post_votes", :only => [:create, :destroy]
    resource :flag, controller: 'post_flags', only: [:destroy]
    resources :favorites, :controller => "post_favorites", :only => [:index]
    collection do
      get :random
    end
    member do
      get :update_iqdb
      put :revert
      put :copy_notes
      get :show_seq
      put :mark_as_translated
      get :comments, to: "comments#for_post"
    end
    get :similar, :to => "iqdb_queries#index"
  end
  resources :post_votes, only: [:index, :delete, :lock] do
    collection do
      post :lock
      post :delete
    end
  end
  resources :post_events, only: :index
  resources :post_flags, except: [:destroy]
  resources :post_approvals, only: [:index]
  resources :post_versions, :only => [:index] do
    member do
      put :undo
    end
  end
  resource :related_tag, :only => [:show, :update]
  match "related_tag/bulk", to: "related_tags#bulk", via: [:get, :post]
  resource :session, only: [:new, :create, :destroy]
  resources :stats, only: [:index]
  resources :tags do
    resource :correction, :only => [:new, :create, :show], :controller => "tag_corrections"
    collection do
      get :autocomplete
      post :preview
    end
  end
  resources :tag_type_versions
  resources :tag_aliases do
    member do
      post :approve
    end
  end
  resource :tag_alias_request, :only => [:new, :create]
  resources :tag_implications do
    member do
      post :approve
    end
  end
  resource :tag_implication_request, :only => [:new, :create]
  resources :uploads
  resources :users do
    resource :password, :only => [:edit], :controller => "maintenance/user/passwords"
    resource :api_key, :only => [:show, :view, :update, :destroy], :controller => "maintenance/user/api_keys" do
      post :view
    end
    resources :staff_notes, only: [:index, :new, :create], controller: "admin/staff_notes"

    collection do
      get :home
      get :search
      get :upload_limit
      get :custom_style
    end
  end
  resources :user_feedbacks do
    collection do
      get :search
    end
  end
  resources :user_name_change_requests
  resource :user_revert, :only => [:new, :create]
  resources :wiki_pages do
    member do
      put :revert
    end
    collection do
      get :search
      get :show_or_new
    end
  end
  resources :wiki_page_versions, :only => [:index, :show, :diff] do
    collection do
      get :diff
    end
  end
  resources :blips do
    member do
      post :hide
      post :unhide
      post :warning
    end
  end
  resources :post_report_reasons
  resources :post_sets do
    collection do
      get :for_select
    end
    member do
      get :maintainers
      get :post_list
      post :update_posts
      post :add_posts
      post :remove_posts
    end
  end
  resources :post_set_maintainers do
    member do
      get :approve
      get :block
      get :deny
    end
  end
  resource :email do
    collection do
      get :activate_user
      get :resend_confirmation
    end
  end
  resources :mascots, only: [:index, :new, :create, :edit, :update, :destroy]

  options "*all", to: "application#enable_cors"

  # aliases
  resources :wpages, :controller => "wiki_pages"
  resources :ftopics, :controller => "forum_topics"
  resources :fposts, :controller => "forum_posts"

  # legacy aliases
  get "/artist" => redirect {|params, req| "/artists?page=#{req.params[:page]}&search[name]=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/index" => redirect {|params, req| "/artists?page=#{req.params[:page]}"}
  get "/artist/show/:id" => redirect("/artists/%{id}")
  get "/artist/show" => redirect {|params, req| "/artists?name=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/history/:id" => redirect("/artist_versions?search[artist_id]=%{id}")
  get "/artist/recent_changes" => redirect("/artist_versions")

  get "/comment" => redirect {|params, req| "/comments?page=#{req.params[:page]}"}
  get "/comment/index" => redirect {|params, req| "/comments?page=#{req.params[:page]}"}
  get "/comment/show/:id" => redirect("/comments/%{id}")
  get "/comment/new" => redirect("/comments")
  get("/comment/search" => redirect do |params, req|
    if req.params[:query] =~ /^user:(.+)/i
      "/comments?group_by=comment&search[creator_name]=#{CGI::escape($1)}"
    else
      "/comments/search"
    end
  end)

  get "/favorite" => redirect {|params, req| "/favorites?page=#{req.params[:page]}"}
  get "/favorite/index" => redirect {|params, req| "/favorites?page=#{req.params[:page]}"}

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  respond_to :html
  before_action :member_only, except: [:index]
  before_action :moderator_only, only: [:update, :edit, :destroy, :claim, :unclaim]

  def index
    @tickets = Ticket.search(search_params).paginate(params[:page], limit: params[:limit])
    respond_with(@tickets)
  end

  def new
    @ticket = Ticket.new(qtype: params[:qtype], disp_id: params[:disp_id])
    check_new_permission(@ticket)
  end

  def create
    @ticket = Ticket.new(ticket_params)
    check_new_permission(@ticket)
    if @ticket.valid?
      @ticket.save
      @ticket.push_pubsub('create')
      flash[:notice] = 'Ticket created'
      redirect_to(ticket_path(@ticket))
    else
      respond_with(@ticket)
    end
  end

  def show
    @ticket = Ticket.find(params[:id])
    check_permission(@ticket)
    respond_with(@ticket)
  end

  def update
    @ticket = Ticket.find(params[:id])
    @ticket.transaction do
      if @ticket.claimant_id.present? && @ticket.claimant_id != CurrentUser.id && params[:force_claim] != 'true'
        flash[:notice] = "Ticket has already been claimed by somebody else, submit again to force."
        redirect_to ticket_path(@ticket, force_claim: 'true')
        return
      end
      ticket_params = update_ticket_params
      if @ticket.warnable? && ticket_params[:record_type].present?
        @ticket.content.user_warned!(ticket_params[:record_type].to_i, CurrentUser.user)
      end
      @ticket.handler_id = CurrentUser.id
      @ticket.claimant_id = CurrentUser.id
      @ticket.update(ticket_params)
      @ticket.push_pubsub('update')
    end

    respond_with(@ticket)
  end

  def claim
    @ticket = Ticket.find(params[:id])

    if @ticket.claimant.nil?
      @ticket.claim!
      redirect_to ticket_path(@ticket)
      return
    end
    flash[:notice] = 'Ticket already claimed.'
    redirect_to ticket_path(@ticket)
  end

  def unclaim
    @ticket = Ticket.find(params[:id])

    if @ticket.claimant.nil?
      flash[:notice] = 'Ticket not claimed.'
      redirect_to ticket_path(@ticket)
      return
    elsif @ticket.claimant.id != CurrentUser.id
      flash[:notice] = 'Ticket not claimed by you.'
      redirect_to ticket_path(@ticket)
      return
    end
    @ticket.unclaim!
    flash[:notice] = 'Claim removed.'
    redirect_to ticket_path(@ticket)
  end

  private

  def ticket_params
    params.require(:ticket).permit(%i[qtype disp_id reason report_reason])
  end

  def update_ticket_params
    params.require(:ticket).permit(%i[response status record_type])
  end

  def search_params
    current_search_params = params.fetch(:search, {})
    permitted_params = %i[qtype status order]
    permitted_params += %i[creator_id] if CurrentUser.is_moderator? || (current_search_params[:creator_id].present? && current_search_params[:creator_id].to_i == CurrentUser.id)
    permitted_params += %i[creator_name accused_name accused_id claimant_id reason] if CurrentUser.is_moderator?
    permit_search_params permitted_params
  end

  def check_new_permission(ticket)
    unless ticket.can_create_for?(CurrentUser.user)
      raise User::PrivilegeError
    end
  end

  def check_permission(ticket)
    unless ticket.can_see_details?(CurrentUser.user)
      raise User::PrivilegeError
    end
  end
end

app/helpers/ticket_helper.rb
module TicketHelper
  def pretty_ticket_status(ticket)
    status = ticket.status
    if status == "partial"
      "Under Investigation"
    elsif status == "approved"
      "Investigated"
    else
      status.titleize
    end
  end
end

app/views/tickets/new_types/_blip.html.erb
<% @blip = @ticket.content %>
<h4>You are reporting the following blip:</h4>
<div class="author"><%= link_to_user(@blip.creator) %></div>
<span class="date" title="Posted on <%= @blip.created_at.strftime("%b %d, %Y %I:%M %p") %>"><%= time_ago_in_words(@blip.created_at) %> ago</span>
<br><br>
<div class="dtext-container">
  <%= format_text(@blip.body) %>
</div>

app/views/tickets/new_types/_comment.html.erb
<% @comment = @ticket.content %>
<h4>You are reporting the following comment:</h4>
<div class="author"><%= link_to_user @comment.creator %></div>
<span class="date" title="Posted on <%= @comment.created_at.strftime("%b %d, %Y %I:%M %p") %>"><%= time_ago_in_words(@comment.created_at) %> ago</span>
<br><br>
<div class="dtext-container">
  <%= format_text(@comment.body) %>
</div>

app/views/tickets/new_types/_dmail.html.erb
<% @dmail = @ticket.content %>
<h4>You are reporting the following private message:</h4>
<div class='author'><%= link_to_user @dmail.from %></div>
<span class="date" title="Sent on <%= @dmail.created_at.strftime("%b %d, %Y %I:%M %p") %>"><%= time_ago_in_words(@dmail.created_at) %>
  ago</span>
<br><br>
<div class="dtext-container">
  <%= format_text(@dmail.body) %>
</div>

app/views/tickets/new_types/_forum.html.erb
<% @forum = @ticket.content %>
<h4>You are reporting the following forum post:</h4>
<div class='author'><%= link_to_user(@forum.creator) %></div>
<span class="date" title="Posted on <%= @forum.created_at.strftime("%b %d, %Y %I:%M %p") %>"><%= time_ago_in_words(@forum.created_at) %> ago</span>
<br><br>
<div class="dtext-container">
  <%= format_text(@forum.body) %>
</div>

app/views/tickets/new_types/_pool.html.erb
<% @pool = @ticket.content %>
<h4>You are reporting the following pool:</h4>
<div class='page'><%= link_to(@pool.name, pool_path(@pool)) %></div>
<div class='author'><%= link_to_user(@pool.creator) %></div>
<span class="date" title="Created on <%= @pool.created_at.strftime("%b %d, %Y %I:%M %p") %>">
  <%= time_ago_in_words(@pool.created_at) %> ago
</span>

app/views/tickets/new_types/_post.html.erb
<% @post = @ticket.content %>
You are reporting <%= PostPresenter.preview(@post, show_deleted: true, no_blacklist: true) %>

<p class="nomargin">Reason:
  <%= select :ticket, :report_reason, options_for_select(PostReportReason.for_select) %>
  <span id="post_reason_description">You must select a reason.</span>
</p>
<%= javascript_tag nonce: true do -%>
  var post_report_reasons = <%= PostReportReason.for_select_descriptions.to_json.html_safe %>;
  $('#ticket_report_reason').on('change', function(e) {
      var description = post_report_reasons[this.options[this.selectedIndex].value] || "You must select a reason.";
      $('#post_reason_description').text(description);
  });
<% end -%>

app/views/tickets/new_types/_set.html.erb
<% @set = @ticket.content %>
<h4>You are reporting the following set:</h4>
<div class='page'><%= link_to(@set.name, post_set_path(@set)) %></div>
<div class='author'><%= link_to_user(@set.creator) %></div>
<span class="date" title="Created on <%= @set.created_at.strftime("%b %d, %Y %I:%M %p") %>"><%= time_ago_in_words(@set.created_at) %> ago</span>

app/views/tickets/new_types/_user.html.erb
You are reporting/commending <%= link_to_user(@ticket.content) %>.

app/views/tickets/new_types/_wiki.html.erb
<% @wiki = @ticket.content %>
<h4>You are reporting the following wiki page:</h4>
<div class='page'><%= link_to_wiki @wiki.title %></div>
<span class="date" title="Posted on <%= @wiki.created_at.strftime("%b %d, %Y %I:%M %p") %>"><%= time_ago_in_words(@wiki.created_at) %> ago</span>
<br><br>
<div class="dtext-container">
  <%= format_text(@wiki.body) %>
</div>