config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  require 'sidekiq_unique_jobs/web'

  mount Sidekiq::Web => '/sidekiq', constraints: AdminRouteConstraint.new

  namespace :admin do
    resources :users, :only => [:edit, :update, :edit_blacklist, :update_blacklist, :alt_list] do
      member do
        get :edit_blacklist
        post :update_blacklist
        get :request_password_reset
        post :password_reset
      end
      collection do
        get :alt_list
      end
    end
    resource :dashboard, :only => [:show]
    resources :exceptions, only: [:index, :show]
    resource :reowner, controller: 'reowner', only: [:new, :create]
    resources :staff_notes, only: [:index]
    resources :danger_zone, only: [:index] do
      collection do
        put :uploading_limits
      end
    end
  end
  resources :edit_histories
  namespace :moderator do
    resource :dashboard, :only => [:show]
    resources :ip_addrs, :only => [:index] do
      collection do
        get :export
      end
    end
    namespace :post do
      resource :approval, :only => [:create, :destroy]
      resources :disapprovals, :only => [:create, :index]
      resources :posts, :only => [:delete, :undelete, :expunge, :confirm_delete] do
        member do
          get :confirm_delete
          post :expunge
          post :delete
          post :undelete
          get :confirm_move_favorites
          post :move_favorites
          get :confirm_ban
          post :ban
          post :unban
          post :regenerate_thumbnails
          post :regenerate_videos
        end
      end
    end
  end
  resources :popular, only: [:index]
  namespace :maintenance do
    namespace :user do
      resource :count_fixes, only: [:new, :create]
      resource :email_notification, :only => [:show, :destroy]
      resource :password_reset, :only => [:new, :create, :edit, :update]
      resource :login_reminder, :only => [:new, :create]
      resource :deletion, :only => [:show, :destroy]
      resource :email_change, :only => [:new, :create]
      resource :dmail_filter, :only => [:edit, :update]
      resource :api_key, :only => [:show, :view, :update, :destroy] do
        post :view
      end
    end
  end

  resources :tickets do
    member do
      post :claim
      post :unclaim
    end
  end

  resources :takedowns do
    collection do
      post :count_matching_posts
    end
    member do
      post :add_by_ids
      post :add_by_tags
      post :remove_by_ids
    end
  end

  resources :artists do
    member do
      put :revert
    end
    collection do
      get :show_or_new
    end
  end
  resources :artist_urls, only: [:index, :update]
  resources :artist_versions, :only => [:index] do
    collection do
      get :search
    end
  end
  resources :bans
  resources :bulk_update_requests do
    member do
      post :approve
    end
  end
  resources :comments do
    resource :votes, :controller => "comment_votes", :only => [:create, :destroy]
    collection do
      get :search
    end
    member do
      post :hide
      post :unhide
      post :warning
    end
  end
  resources :comment_votes, only: [:index, :delete, :lock] do
    collection do
      post :lock
      post :delete
    end
  end
  resources :dmails, :only => [:new, :create, :index, :show, :destroy] do
    collection do
      post :mark_all_as_read
    end
  end
  resource :dtext_preview, :only => [:create]
  resources :favorites, :only => [:index, :create, :destroy]
  resources :forum_posts do
    resource :votes, controller: "forum_post_votes"
    member do
      post :hide
      post :unhide
      post :warning
    end
    collection do
      get :search
    end
  end
  resources :forum_topics do
    member do
      post :hide
      post :unhide
      post :subscribe
      post :unsubscribe
    end
    collection do
      post :mark_all_as_read
    end
    resource :visit, :controller => "forum_topic_visits"
  end
  resources :forum_categories
  resources :help_pages, controller: "help", path: "help"
  resources :ip_bans
  resources :upload_whitelists do
    collection do
      get :is_allowed
    end
  end
  resources :email_blacklists, only: [:new, :create, :destroy, :index]
  resource :iqdb_queries, :only => [:show] do
    collection do
      post :show
      get :preview
      get :check, to: redirect {|path_params, req| "/iqdb_queries?#{req.query_string}"}
    end
  end
  resources :mod_actions
  resources :news_updates
  resources :notes do
    collection do
      get :search
    end
    member do
      put :revert
    end
  end
  resources :note_versions, :only => [:index]
  resource :note_previews, :only => [:show]
  resources :pools do
    member do
      put :revert
    end
    collection do
      get :gallery
    end
    resource :order, :only => [:edit], :controller => "pool_orders"
  end
  resource :pool_element, :only => [:create, :destroy]
  resources :pool_versions, :only => [:index] do
    member do
      get :diff
    end
  end
  resources :post_replacements, :only => [:index, :new, :create, :destroy] do
    member do
      put :approve
      put :reject
      post :promote
      put :toggle_penalize
    end
  end
  resources :deleted_posts, only: [:index]
  resources :posts, :only => [:index, :show, :update] do
    resources :replacements, :only => [:index, :new, :create], :controller => "post_replacements"
    resource :votes, :controller => "post_votes", :only => [:create, :destroy]
    resource :flag, controller: 'post_flags', only: [:destroy]
    resources :favorites, :controller => "post_favorites", :only => [:index]
    collection do
      get :random
    end
    member do
      get :update_iqdb
      put :revert
      put :copy_notes
      get :show_seq
      put :mark_as_translated
      get :comments, to: "comments#for_post"
    end
    get :similar, :to => "iqdb_queries#index"
  end
  resources :post_votes, only: [:index, :delete, :lock] do
    collection do
      post :lock
      post :delete
    end
  end
  resources :post_events, only: :index
  resources :post_flags, except: [:destroy]
  resources :post_approvals, only: [:index]
  resources :post_versions, :only => [:index] do
    member do
      put :undo
    end
  end
  resource :related_tag, :only => [:show, :update]
  match "related_tag/bulk", to: "related_tags#bulk", via: [:get, :post]
  resource :session, only: [:new, :create, :destroy]
  resources :stats, only: [:index]
  resources :tags do
    resource :correction, :only => [:new, :create, :show], :controller => "tag_corrections"
    collection do
      get :autocomplete
      post :preview
    end
  end
  resources :tag_type_versions
  resources :tag_aliases do
    member do
      post :approve
    end
  end
  resource :tag_alias_request, :only => [:new, :create]
  resources :tag_implications do
    member do
      post :approve
    end
  end
  resource :tag_implication_request, :only => [:new, :create]
  resources :uploads
  resources :users do
    resource :password, :only => [:edit], :controller => "maintenance/user/passwords"
    resource :api_key, :only => [:show, :view, :update, :destroy], :controller => "maintenance/user/api_keys" do
      post :view
    end
    resources :staff_notes, only: [:index, :new, :create], controller: "admin/staff_notes"

    collection do
      get :home
      get :search
      get :upload_limit
      get :custom_style
    end
  end
  resources :user_feedbacks do
    collection do
      get :search
    end
  end
  resources :user_name_change_requests
  resource :user_revert, :only => [:new, :create]
  resources :wiki_pages do
    member do
      put :revert
    end
    collection do
      get :search
      get :show_or_new
    end
  end
  resources :wiki_page_versions, :only => [:index, :show, :diff] do
    collection do
      get :diff
    end
  end
  resources :blips do
    member do
      post :hide
      post :unhide
      post :warning
    end
  end
  resources :post_report_reasons
  resources :post_sets do
    collection do
      get :for_select
    end
    member do
      get :maintainers
      get :post_list
      post :update_posts
      post :add_posts
      post :remove_posts
    end
  end
  resources :post_set_maintainers do
    member do
      get :approve
      get :block
      get :deny
    end
  end
  resource :email do
    collection do
      get :activate_user
      get :resend_confirmation
    end
  end
  resources :mascots, only: [:index, :new, :create, :edit, :update, :destroy]

  options "*all", to: "application#enable_cors"

  # aliases
  resources :wpages, :controller => "wiki_pages"
  resources :ftopics, :controller => "forum_topics"
  resources :fposts, :controller => "forum_posts"

  # legacy aliases
  get "/artist" => redirect {|params, req| "/artists?page=#{req.params[:page]}&search[name]=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/index" => redirect {|params, req| "/artists?page=#{req.params[:page]}"}
  get "/artist/show/:id" => redirect("/artists/%{id}")
  get "/artist/show" => redirect {|params, req| "/artists?name=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/history/:id" => redirect("/artist_versions?search[artist_id]=%{id}")
  get "/artist/recent_changes" => redirect("/artist_versions")

  get "/comment" => redirect {|params, req| "/comments?page=#{req.params[:page]}"}
  get "/comment/index" => redirect {|params, req| "/comments?page=#{req.params[:page]}"}
  get "/comment/show/:id" => redirect("/comments/%{id}")
  get "/comment/new" => redirect("/comments")
  get("/comment/search" => redirect do |params, req|
    if req.params[:query] =~ /^user:(.+)/i
      "/comments?group_by=comment&search[creator_name]=#{CGI::escape($1)}"
    else
      "/comments/search"
    end
  end)

  get "/favorite" => redirect {|params, req| "/favorites?page=#{req.params[:page]}"}
  get "/favorite/index" => redirect {|params, req| "/favorites?page=#{req.params[:page]}"}

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :member_only, :only => [:edit, :update, :preview]
  respond_to :html, :json

  def edit
    @tag = Tag.find(params[:id])
    check_privilege(@tag)
    respond_with(@tag)
  end

  def index
    @tags = Tag.search(search_params).paginate(params[:page], :limit => params[:limit], :search_count => params[:search])

    respond_with(@tags)
  end

  def autocomplete
    @tags = Tag.names_matches_with_aliases(params[:search][:name_matches])

    expires_in params[:expiry].to_i.days if params[:expiry]

    respond_with(@tags) do |fmt|
      fmt.json do
        render json: @tags.to_json
      end
    end
  end

  def preview
    @preview = TagsPreview.new(tags: params[:tags])
    respond_to do |format|
      format.json do
        render json: @preview.serializable_hash
      end
    end
  end

  def show
    if params[:id] =~ /\A\d+\z/
      @tag = Tag.find(params[:id])
    else
      @tag = Tag.find_by!(name: params[:id])
    end
    respond_with(@tag)
  end

  def update
    @tag = Tag.find(params[:id])
    check_privilege(@tag)
    @tag.update(tag_params)
    respond_with(@tag)
  end

  private

  def check_privilege(tag)
    raise User::PrivilegeError unless tag.category_editable_by?(CurrentUser.user)
  end

  def tag_params
    permitted_params = [:category]
    permitted_params << :is_locked if CurrentUser.is_moderator?

    params.require(:tag).permit(permitted_params)
  end

  def allowed_readonly_actions
    super + %w[autocomplete]
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def alias_and_implication_list(tag)
    return "" if tag.nil?

    html = ""

    if tag.antecedent_alias
      html << "<p class='hint'>This tag has been aliased to "
      html << link_to(tag.antecedent_alias.consequent_name, show_or_new_wiki_pages_path(:title => tag.antecedent_alias.consequent_name))
      html << " (#{link_to "learn more", wiki_pages_path(title: "e621:tag_aliases")}).</p>"
    end

    if tag.consequent_aliases.present?
      html << "<p class='hint'>The following tags are aliased to this tag: "
      html << raw(tag.consequent_aliases.map {|x| link_to(x.antecedent_name, show_or_new_wiki_pages_path(:title => x.antecedent_name))}.join(", "))
      html << " (#{link_to "learn more", wiki_pages_path(title: "e621:tag_aliases")}).</p>"
    end

    if tag.antecedent_implications.present?
      html << "<p class='hint'>This tag implicates "
      html << raw(tag.antecedent_implications.map {|x| link_to(x.consequent_name, show_or_new_wiki_pages_path(:title => x.consequent_name))}.join(", "))
      html << " (#{link_to "learn more", wiki_pages_path(title: "e621:tag_implications")}).</p>"
    end

    if tag.consequent_implications.present?
      html << "<p class='hint'>The following tags implicate this tag: "
      html << raw(tag.consequent_implications.map {|x| link_to(x.antecedent_name, show_or_new_wiki_pages_path(:title => x.antecedent_name))}.join(", "))
      html << " (#{link_to "learn more", wiki_pages_path(title: "e621:tag_implications")}).</p>"
    end

    html.html_safe
  end

  def format_transitive_item(transitive)
    html = "<strong class=\"redtext\">#{transitive[0].to_s.titlecase}</strong> ".html_safe
    if transitive[0] == :alias
      html << "#{transitive[2]} -> #{transitive[3]} will become #{transitive[2]} -> #{transitive[4]}"
    else
      html << "#{transitive[2]} +> #{transitive[3]} will become #{transitive[4]} +> #{transitive[5]}"
    end
    html
  end
end

app/views/tags/_quick_search.html.erb
<%= form_tag(tags_path, :method => :get) do %>
  <%= text_field "search", "name_matches", :id => "quick_search_name_matches", :placeholder => "Search tags", :data => { :autocomplete => "tag" } %>
<% end %>

app/views/tags/_search.html.erb
<%= form_search(path: tags_path) do |f| %>
  <%= f.input :name_matches, label: "Name", hint: "Use * for wildcard", autocomplete: "tag" %>
  <%= f.input :category, label: "Category", collection: TagCategory.canonical_mapping.to_a, include_blank: true %>
  <%= f.input :order, collection: [%w[Newest date], %w[Count count], %w[Name name]], include_blank: false %>
  <%= f.input :has_wiki, label: "Has wiki?", collection: %w[yes no], include_blank: true %>
  <%= f.input :has_artist, label: "Has artist?", collection: %w[yes no], include_blank: true %>
  <%= f.input :hide_empty, label: "Hide empty?", as: :boolean, default: true %>
  <%= f.submit "Search" %>
<% end %>

app/views/tags/_secondary_links.html.erb
<% content_for(:secondary_links) do %>
  <menu>
    <li><%= render "tags/quick_search" %></li>
    <%= subnav_link_to "Listing", tags_path %>
    <%= subnav_link_to "MetaSearch", meta_searches_tags_path %>
    <%= subnav_link_to "Aliases", tag_aliases_path %>
    <%= subnav_link_to "Implications", tag_implications_path %>
    <%= subnav_link_to "Bulk updates", bulk_update_requests_path %>
    <%= subnav_link_to "Related tags", related_tag_path %>
    <%= subnav_link_to "Cheatsheet", help_page_path(id: "cheatsheet") %>
    <%= subnav_link_to "Help", help_page_path(id: "tags") %>
    <% if @tag %>
      <li>|</li>
      <%= subnav_link_to "Posts (#{@tag.post_count})", posts_path(tags: @tag.name) %>
      <%= subnav_link_to "Wiki Page", show_or_new_wiki_pages_path(title: @tag.name) %>
      <%= subnav_link_to "Edit", edit_tag_path(@tag) %>
      <%= subnav_link_to "Category History", tag_type_versions_path(search: { tag: @tag.name }) %>
      <% if CurrentUser.is_janitor? %>
        <%= subnav_link_to "Fix", new_tag_correction_path(tag_id: @tag.id) %>
      <% end %>
    <% end %>
  </menu>
<% end %>

app/views/tags/edit.html.erb
<div id="c-tags">
  <div id="a-edit">
    <h1>Tag: <%= link_to @tag.name, posts_path(:tags => @tag.name), :class => "tag-type-#{@tag.category}" %></h1>

    <%= custom_form_for(@tag) do |f| %>
      <% if @tag.is_locked? %>
        <p>This tag is category locked</p>
      <% else %>
        <%= f.input :category, :collection => TagCategory.canonical_mapping.to_a, :include_blank => false %>
      <% end %>

      <% if CurrentUser.is_moderator? %>
        <%= f.input :is_locked, :collection => [["No", "false"], ["Yes", "true"]], :include_blank => false %>
      <% end %>

      <%= f.button :submit, "Submit" %>
    <% end %>
  </div>
</div>

<%= render "secondary_links" %>

<% content_for(:page_title) do %>
  Edit Tag - <%= @tag.name %>
<% end %>

app/views/tags/index.html.erb
<div id="c-tags">
  <div id="a-index">
    <%= render "search" %>
    <table class="striped">
      <thead>
        <tr>
          <th>Count</th>
          <th>Name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @tags.each do |tag| %>
          <tr>
            <td><%= tag.post_count %></td>
            <td class="category-<%= tag.category %>">
              <% if tag.category == Tag.categories.artist %>
                <%= link_to("?",  show_or_new_artists_path(:name => tag.name)) %>
              <% else %>
                <%= link_to("?", show_or_new_wiki_pages_path(:title => tag.name)) %>
              <% end %>
              <%= link_to(tag.name, posts_path(:tags => tag.name)) %>
            </td>
            <td>
              <% if tag.category_editable_by?(CurrentUser.user) %>
                <%= link_to "edit", edit_tag_path(tag) %>
              <% end %>
              | <%= link_to "history", tag_type_versions_path(search: {tag: tag.name}) %>
              <% if CurrentUser.is_janitor? %>
                | <%= link_to "fix", new_tag_correction_path(:tag_id => tag.id) %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= numbered_paginator(@tags) %>
  </div>
</div>

<%= render "secondary_links" %>

<% content_for(:page_title) do %>
  Tags
<% end %>

app/views/tags/show.html.erb
<div id="c-tags">
  <div id="a-show">
    <h1>Tag: <%= link_to @tag.name, posts_path(:tags => @tag.name), :class => "tag-type-#{@tag.category}" %></h1>

    <ul>
      <li>Count: <%= @tag.post_count %></li>
      <li>Category: <%= @tag.category_name %></li>
    </ul>
  </div>
</div>

<%= render "secondary_links" %>

<% content_for(:page_title) do %>
  Tag - <%= @tag.name %>
<% end %>